# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
